language: r

before_install:
  - cd eSVD2

cache: packages

r_binary_packages:
    - MASS
    - Matrix
    - softImpute
    - RSpectra

after_success:
  - Rscript -e 'library(covr); codecov()'

warnings_are_errors: true
