# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

opt_x_cpp <- function(X0, Y, B, Z, A, family, s, gamma, offset, verbose = 0L) {
    .Call(`_eSVD2_opt_x_cpp`, X0, Y, B, Z, A, family, s, gamma, offset, verbose)
}

opt_yb_cpp <- function(YB0, XZ, A, family, s, gamma, offset, verbose = 0L) {
    .Call(`_eSVD2_opt_yb_cpp`, YB0, XZ, A, family, s, gamma, offset, verbose)
}

objfn_Xi_impl <- function(Xi_, Y_, B_, Zi_, Ai_, family_, si_, gamma_, offseti) {
    .Call(`_eSVD2_objfn_Xi_impl`, Xi_, Y_, B_, Zi_, Ai_, family_, si_, gamma_, offseti)
}

objfn_Yj_impl <- function(Yj_, X_, Bj_, Z_, Aj_, family_, s_, gammaj_, offset) {
    .Call(`_eSVD2_objfn_Yj_impl`, Yj_, X_, Bj_, Z_, Aj_, family_, s_, gammaj_, offset)
}

grad_Xi_impl <- function(Xi_, Y_, B_, Zi_, Ai_, family_, si_, gamma_, offseti) {
    .Call(`_eSVD2_grad_Xi_impl`, Xi_, Y_, B_, Zi_, Ai_, family_, si_, gamma_, offseti)
}

grad_Yj_impl <- function(Yj_, X_, Bj_, Z_, Aj_, family_, s_, gammaj_, offset) {
    .Call(`_eSVD2_grad_Yj_impl`, Yj_, X_, Bj_, Z_, Aj_, family_, s_, gammaj_, offset)
}

hessian_Xi_impl <- function(Xi_, Y_, B_, Zi_, Ai_, family_, si_, gamma_, offseti) {
    .Call(`_eSVD2_hessian_Xi_impl`, Xi_, Y_, B_, Zi_, Ai_, family_, si_, gamma_, offseti)
}

hessian_Yj_impl <- function(Yj_, X_, Bj_, Z_, Aj_, family_, s_, gammaj_, offset) {
    .Call(`_eSVD2_hessian_Yj_impl`, Yj_, X_, Bj_, Z_, Aj_, family_, s_, gammaj_, offset)
}

direction_Xi_impl <- function(Xi_, Y_, B_, Zi_, Ai_, family_, si_, gamma_, offseti) {
    .Call(`_eSVD2_direction_Xi_impl`, Xi_, Y_, B_, Zi_, Ai_, family_, si_, gamma_, offseti)
}

direction_Yj_impl <- function(Yj_, X_, Bj_, Z_, Aj_, family_, s_, gammaj_, offset) {
    .Call(`_eSVD2_direction_Yj_impl`, Yj_, X_, Bj_, Z_, Aj_, family_, s_, gammaj_, offset)
}

distribution_neg_binom <- function() {
    .Call(`_eSVD2_distribution_neg_binom`)
}

distribution_poisson <- function() {
    .Call(`_eSVD2_distribution_poisson`)
}

