# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

opt_x_cpp <- function(X0, Y, B, Z, A, family, s, gamma, offset, l2pen, verbose = 0L) {
    .Call(`_eSVD2_opt_x_cpp`, X0, Y, B, Z, A, family, s, gamma, offset, l2pen, verbose)
}

opt_yb_cpp <- function(YB0, XZ, A, family, s, gamma, offset, l2pen, verbose = 0L) {
    .Call(`_eSVD2_opt_yb_cpp`, YB0, XZ, A, family, s, gamma, offset, l2pen, verbose)
}

objfn_Xi_impl <- function(Xi, Y, B, Zi, Ai, family, si, gamma, offseti, l2pen) {
    .Call(`_eSVD2_objfn_Xi_impl`, Xi, Y, B, Zi, Ai, family, si, gamma, offseti, l2pen)
}

objfn_Yj_impl <- function(Yj, X, Bj, Z, Aj, family, s, gammaj, offset, l2pen) {
    .Call(`_eSVD2_objfn_Yj_impl`, Yj, X, Bj, Z, Aj, family, s, gammaj, offset, l2pen)
}

grad_Xi_impl <- function(Xi, Y, B, Zi, Ai, family, si, gamma, offseti, l2pen) {
    .Call(`_eSVD2_grad_Xi_impl`, Xi, Y, B, Zi, Ai, family, si, gamma, offseti, l2pen)
}

grad_Yj_impl <- function(Yj, X, Bj, Z, Aj, family, s, gammaj, offset, l2pen) {
    .Call(`_eSVD2_grad_Yj_impl`, Yj, X, Bj, Z, Aj, family, s, gammaj, offset, l2pen)
}

hessian_Xi_impl <- function(Xi, Y, B, Zi, Ai, family, si, gamma, offseti, l2pen) {
    .Call(`_eSVD2_hessian_Xi_impl`, Xi, Y, B, Zi, Ai, family, si, gamma, offseti, l2pen)
}

hessian_Yj_impl <- function(Yj, X, Bj, Z, Aj, family, s, gammaj, offset, l2pen) {
    .Call(`_eSVD2_hessian_Yj_impl`, Yj, X, Bj, Z, Aj, family, s, gammaj, offset, l2pen)
}

direction_Xi_impl <- function(Xi, Y, B, Zi, Ai, family, si, gamma, offseti, l2pen) {
    .Call(`_eSVD2_direction_Xi_impl`, Xi, Y, B, Zi, Ai, family, si, gamma, offseti, l2pen)
}

direction_Yj_impl <- function(Yj, X, Bj, Z, Aj, family, s, gammaj, offset, l2pen) {
    .Call(`_eSVD2_direction_Yj_impl`, Yj, X, Bj, Z, Aj, family, s, gammaj, offset, l2pen)
}

gamma_rate <- function(x, mu, s) {
    .Call(`_eSVD2_gamma_rate`, x, mu, s)
}

distribution_neg_binom <- function() {
    .Call(`_eSVD2_distribution_neg_binom`)
}

distribution_neg_binom2 <- function() {
    .Call(`_eSVD2_distribution_neg_binom2`)
}

distribution_poisson <- function() {
    .Call(`_eSVD2_distribution_poisson`)
}

