# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

objfn_Xi_impl <- function(Xi_, Y_, B_, Zi_, Ai_, family_, si_, gamma_) {
    .Call(`_eSVD2_objfn_Xi_impl`, Xi_, Y_, B_, Zi_, Ai_, family_, si_, gamma_)
}

objfn_Yj_impl <- function(Yj_, X_, Bj_, Z_, Aj_, family_, s_, gammaj_) {
    .Call(`_eSVD2_objfn_Yj_impl`, Yj_, X_, Bj_, Z_, Aj_, family_, s_, gammaj_)
}

grad_Xi_impl <- function(Xi_, Y_, B_, Zi_, Ai_, family_, si_, gamma_) {
    .Call(`_eSVD2_grad_Xi_impl`, Xi_, Y_, B_, Zi_, Ai_, family_, si_, gamma_)
}

grad_Yj_impl <- function(Yj_, X_, Bj_, Z_, Aj_, family_, s_, gammaj_) {
    .Call(`_eSVD2_grad_Yj_impl`, Yj_, X_, Bj_, Z_, Aj_, family_, s_, gammaj_)
}

hessian_Xi_impl <- function(Xi_, Y_, B_, Zi_, Ai_, family_, si_, gamma_) {
    .Call(`_eSVD2_hessian_Xi_impl`, Xi_, Y_, B_, Zi_, Ai_, family_, si_, gamma_)
}

hessian_Yj_impl <- function(Yj_, X_, Bj_, Z_, Aj_, family_, s_, gammaj_) {
    .Call(`_eSVD2_hessian_Yj_impl`, Yj_, X_, Bj_, Z_, Aj_, family_, s_, gammaj_)
}

direction_Xi_impl <- function(Xi_, Y_, B_, Zi_, Ai_, family_, si_, gamma_) {
    .Call(`_eSVD2_direction_Xi_impl`, Xi_, Y_, B_, Zi_, Ai_, family_, si_, gamma_)
}

direction_Yj_impl <- function(Yj_, X_, Bj_, Z_, Aj_, family_, s_, gammaj_) {
    .Call(`_eSVD2_direction_Yj_impl`, Yj_, X_, Bj_, Z_, Aj_, family_, s_, gammaj_)
}

distribution_neg_binom <- function() {
    .Call(`_eSVD2_distribution_neg_binom`)
}

distribution_poisson <- function() {
    .Call(`_eSVD2_distribution_poisson`)
}

